# Use the latest Debian stable version
FROM mcr.microsoft.com/dotnet/sdk:8.0

# Install Zsh and Oh My Zsh
RUN apt-get update && apt-get install -y zsh wget git \
    && sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
    && chsh -s $(which zsh) \

    && apt-get install -y locales locales-all \
    && update-locale

# Set up Oh My Zsh with a theme and plugins
RUN rm -rf ~/.oh-my-zsh \
    && git clone https://github.com/powerline/fonts.git \
    && cd fonts \
    && ./install.sh \
    && cd .. && rm -rf fonts \
    && git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh \
    && cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc \
    && sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/' ~/.zshrc \
    && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting \
    && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions \
    && sed -i 's/plugins=(git)/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/' ~/.zshrc

# Set the default shell to Zsh
SHELL ["/usr/bin/zsh", "-c"]

# Install any additional dependencies or tools you need
# RUN apt-get install -y <additional-tools>

RUN dotnet tool install --global dotnet-outdated-tool
ENV PATH="${PATH}:/root/.dotnet/tools"

# Set up the working directory
WORKDIR /workspace

# Expose any necessary ports
# EXPOSE 8080

# Command to run when the container starts
CMD ["zsh"]
