### Add a new Movie

POST {{baseUrl}}/movies HTTP/1.1
Content-Type: application/json

{   
    "movie": { "title": "The Matrix",
    "plot": "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence."
  }
}

