### Get movie by Id

@movieId = 6766fcea0c7c363d178c876f

GET {{baseUrl}}/movies/{{movieId}} HTTP/1.1
Accept-Encoding: gzip
Content-Encoding: gzip

### Get all movies

@pageNumber = 1
@pageSize = 100

GET {{baseUrl}}/movies?pageNumber={{pageNumber}}&pageSize={{pageSize}} HTTP/1.1
Accept-Encoding: gzip
Content-Encoding: gzip