### Get movie by Id

@movieId = 573a1390f29313caabcd42e8

GET {{baseUrl}}/movies/{{movieId}} HTTP/1.1

### Get all movies

@pageNumber = 1
@pageSize = 10

GET {{baseUrl}}/movies?pageNumber={{pageNumber}}&pageSize={{pageSize}} HTTP/1.1